### ISSUE TITLE
proto2 vs proto3, field serialization, dontOmit

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-protobuf-serialization#4]
Recapping the discussion on optional and required fields, and how proto2 differs from proto3:

In proto2, fields can be set or not set, and required or optional.  When a field is optional, it can also have a default value, meaning that if a stream is parsed and there is no value in the stream, the default should be used, and this default can be set per field. However, if a field is set to the default value, it must still be sent in the stream - per instance - meaning that I can create one message with the field set, another without it, and they will result in different binary streams. Thus, to correctly implement parsing, for every field, there also needs to be present a `set flag` which highlights if the field was set or not - at the very least, the library must offer up this possibility, for example using a library-defined type similar, but not the same as, `Optional` - likewise for serializing: if I don't set a required field explicitly, the serializer should give me an error - I may however set the value to the default - this is fine / correct, and should result in the value being sent over the wire.

Some protocols in proto2 rely on this distinction: for example, setting an integer to 0 is not the same as not setting it at all, and in proto2 this is information that can be used in the protocol.

In proto3, all fields are optional, and the language generally makes no distinction between set and unset fields, even if the distinction continues to exist on the wire. Also, user-selected defaults were removed from the language and everything is now initialized to  0. A field that is set to the default value _may_ be omitted from the stream - it makes no difference.

A `dontOmit` annotation on the field does not work for proto2 - sometimes the value should be sent, and sometimes not - depending on whether it was explicitly set on that particular message instance or not. In proto3, `dontOmit` doesn't make sense at all - there's no distinction between an explicitly sent value and one that wasn't sent.

Arguably, `proto3` is easier to implement in nim (because, for example, the zero-init works the same way and there's no need to keep track of set/unset), to the extent that it would make sense to have 2 flavours of the protobuf writers/readers, as well as annotations.  

`proto2` is a significantly different language with more complex semantics, and if the library takes shortcuts or invents its own extensions like `dontOmit`, or tries to cram both languages into the same box, some protocols will not be representable and users will be confused.

For more background, see the language guide: 
* proto3 - https://developers.google.com/protocol-buffers/docs/proto3#default_values
* proto2 - https://developers.google.com/protocol-buffers/docs/proto2#default_values

**Comment by zah** [comment]
Thanks for this explanation, but I need a clarification on one point. Why is the `Option[T]` type not sufficient to represent the semantics of both Proto2 and Proto3? Why do we need a different `Optional` type?

If `Proto2` and `Proto3` are considered different formats, the serialization of `Option[T]` can be defined as follows:

In Proto2 (pseudo-code):

```nim
if option.isSome:
  output.write fieldId, option.get()
```

In Proto3:

```nim
if option.isSome and not option.get.isDefault:
  output.write fieldId, option.get()
```

Thus, the user just needs to use the `Option[T]` type in their fields if compatibility and full expressivity with both formats is desired. The default value used when the field is omitted in Proto2 can be specified as a Proto2-specific pragma (this doesn't hurt any other format).

Now, you can argue that the use of `Option[T]` has implications for other formats (e.g. SSZ), but this is not a problem we are having in practice and I can imagine some ways to address it with a reader-bound bitmask (there will be a format-specific `decode` flavour that populates a bitmask object that can be used to check for the presence of fields).

You can also argue that the default value construction in Proto2 is lazy (it happens when the function to read the field value is executed) and our treatment based on the default value pragma will have to be eager (it happens while the object is being decoded). This may be indeed an argument for a custom `Optional` type with a default value attached as a static parameter, but there are some very fine trade-offs between attaching the default value to the type vs to the field symbol:

* Attaching it to the type helps if you are going to pass these values around to functions that should not lose the "metadata".
* Attaching it to the symbol helps if you need to pass these values to existing code working with a more traditional type.

It's true though that you can always make the custom type a wrapper/distinct type that can be easily stripped away.

**Comment by arnetheduck** [comment]
I would not complicate the discussion with SSZ - SSZ is another, significantly incompatible format - that should go in a separate discussion on how to map one format to the other (because there are things in each of the format that you cannot express naturally in the other).

`Option[T]` gets close but fails to capture default values and `optional` semantics when reading and there's no value in the stream, or when constructing a new instance - generally, when reading an optional field value, you want there to be no distinction between set and unset - this becomes more quirky with `Option` - the getter raises a defect - so you have to invent something that causes it to not behave like `Option` any more (more like `Option.getOrDefault`) - at that point you're effectively looking at a different type.

If the only concern was serializing (writing), `Option` would indeed be enough for both languages - though for `proto3` it would be overly complicated - in proto3 `if field != default:  output.write fieldId; ...` is a sufficient condition.

In protobuf implementations for other languages, code gets generated that encodes the default values with the type - a solution like we did with `List` for SSZ would be quite appropriate - it would have its own API that would be tailored to how the type behaves in protobuf - if ever we wanted to make the two formats interoperable, it would also provide us with the type information that's necessary to properly "hook" into the system and implement the translation, because ultimately, the mapping between the two languages is somewhat arbitrary since the rules are different - the same thing happens when mapping protobuf to json: there are several possible ways to perform the translation, and for proto3 (with its more simple semantics), google proposes a canonical mapping, but that doesn't mean it's the _only_ way)

**Comment by arnetheduck** [comment]
It's also worth noting that `proto2` and `proto3` are incompatible formats - the value in keeping them compatible from a declaration point of view is somewhat limited, because practically, protocols use either proto2 or proto3 - they don't use both in the same "module" so the same nim type will not be used with both proto2 and proto3 at the same time.

**Comment by arnetheduck** [comment]
In fact, I find that it's more useful to start this discussion at the opposite end, just like google does:  proto2 and proto3 are two incompatible serialization languages that incidentally share the underlying wire encoding. 

As such, they should be approached with different mindsets, and above all independently, from a usage point-of-view. Once the two are individually working to satisfaction, one can seek commonalities.

**Comment by arnetheduck** [comment]
Thinking more about `Option[T]` for `proto3`, it's questionable whether it should be allowed at all - it doesn't have the semantics of the `proto3` language and may fool the user into believing that it behaves like option - ie that if you set an option, you get a set option on the other end, when roundtripping - this quirk would be specially dangerous when trying to interop with other langauges.

**Comment by oskarth** [comment]
For clarification - is this library:
a) 100% compatible with protobuf3
b) 100% compatible with protobuf2
c) 100% compatible with both protobuf2 and protobuf3
d) Not 100% compatible with either

My current understanding from skimming above is a, but I'm definitely not sure of this.

As a potential user of this library, it'd be good to have this documented clearly, in README e.g, along with specific caveats.

**Comment by oskarth** [comment]
Can we transfer issues from https://github.com/kayabaNerve/nim-protobuf-serialization/issues/32 etc to this repo btw?

**Comment by kayabaNerve** [comment]
It's 100% compatible with the PB wire encoding. Its high-level semantics and functionality is equivalent to PB 3, yet PB 2 can be achieved, with extra work on the user's end, via `dontOmit` (horribly named; it's `required` yet only applies to writing and adds no checks to reading) and Options. That said, any user parsing will have to check each Option is set/not-set accordingly, as well as supply a default value in the not-set case, so it quickly becomes annoying and impractical.

If we want to hold off on splitting the library, it sounds like the tasks can be divided as follows:
1) Add a PB 2/PB 3 pragma that must be attached to every PB serialized object.
2) Rename dontOmit to required.
3) Require fields with the required pragma be read from any parsed data. Else, raise.
4) Require every PB 2 field which isn't required to be a PBOption, which always has an automatic default.

That said, it does sound like the discussion is about splitting the library at this point. Before that discussion continues, I'd like to make a note. This isn't a PB 2 library. This also isn't a PB 3 library. It's explicitly a PB binary wire library. The pragmas/macros were chosen to enable PB features and be easy to pick up. To that end, yes, they adopted PB 3 semantics, as I said at the start.

Instead of splitting this library, it may be better to ship two frontends; in their own libraries or even bundled in here. Even though it's easy enough to fork this, the two libraries still share a lot of code. The required/optional differences are significant, yes, but they share the same write/read field functions.

**Comment by oskarth** [comment]
Maybe this is a stupid question, but if I want to specify things using a `.proto` file, how does that work? Are there any examples that show this? Or is that not a design goal?

As a potential user of this library, I'd like to:
1. Specify a `.proto` file
2. Indicate which version of protobuf I want to use with e.g. `syntax = "proto2"`
3. Load this file in Nim and have it generate reasonable default types/functions for serialization/deserialization

**Comment by zah** [comment]
That's not a stupid question, @oskarth. We plan to support this by integrating the compile-time .proto files parser from https://github.com/PMunch/protobuf-nim, which will be able to generate the type definitions that the rest of the library requires.

**Comment by kayabaNerve** [comment]
Can this be closed? Protobuf 2/3 is explicitly specified with a pragma on Nim objects. There's a required pragma, and unless it's specified, the data must be an Option. Primitives use PBOption which require setting a default value.

dontOmit has also been purged.

As for file support, PB 3 files work now (mostly). PB 2 isn't supported, and won't be until we improve PMunch's work (which is quality, don't get me wrong; it just needs more love and care put in).

**Comment by arnetheduck** [comment]
There are quite a few more incompatibilities left to deal with - I've opened issues for those, but remaining in this ticket is the removal of the special semantics for `optional` fields - `std/options` simply doesn't match the upstream intent of optional fields and issues with this will ensure when interoperating with other languages - see for example https://github.com/protocolbuffers/protobuf/issues/9332 that makes the same argument for the C++ library.

**Comment by arnetheduck** [comment]
IE the action point here is to completely remove handing of `Option` (and `HashSet`, `ref` and `ptr`) - what should be done instead is to allow pluggable extensions for any type that the user of the library wants to handle in a special way - this extension mechanism should also be able to cover the [well-known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)

**Comment by arnetheduck** [comment]
#36
